import Head from "next/head";
import Image from "next/image";
import styles from "../sass/Home.module.scss";

import Navigation from "../components/Nav/navigation";
import Slides from '../components/Slides/homeSlides';
import Card from '../components/Cards/homeCard';

export default function Home() {

  const services = {
    title:'Services',
    info:['Paint','modeling','basing'],
    route:'/services'  
  }



  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.about}>
            <h1>About</h1>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit.
              Temporibus exercitationem voluptate explicabo veritatis suscipit
              minus repellat magni modi vero, fuga aliquid fugiat tempore
              laborum unde veniam rem repudiandae quibusdam animi accusamus
              delectus? Ex molestiae magnam facere. Exercitationem in fugit,
              natus illum laudantium voluptates, illo nulla possimus et quos
              quae eaque.
            </p>
          </div>
          <div className={styles.imgBox}>
            <div className={styles.image}>
              <Image src={"/images/chaosSplotchRed.jpg"} layout="fill" />
            </div>
          </div>
        </div>
        <Slides/>
        <div>
          <Card props={services} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
